project_id = "dovvbtzpawheafcqmdbt"

[functions.invite-user]
verify_jwt = false

[functions.send-credentials]
verify_jwt = false

[functions.ssh-deploy]
verify_jwt = false

[functions.server-stats]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.restore-backup]
verify_jwt = false
